package com.mainsoft.mlp.reconciliation.common.webservice.osb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2017-04-06T19:32:50.854+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/", name = "ServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoap {

    @WebResult(name = "ServiceEntranceResult", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
    @RequestWrapper(localName = "ServiceEntrance", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/", className = "com.mainsoft.mlp.corpus.modules.acp.client2.ServiceEntrance")
    @WebMethod(operationName = "ServiceEntrance", action = "http://www.mainsoft.com.cn/mlp/router1/ServiceEntrance")
    @ResponseWrapper(localName = "ServiceEntranceResponse", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/", className = "com.mainsoft.mlp.corpus.modules.acp.client2.ServiceEntranceResponse")
    public byte[] serviceEntrance(
            @WebParam(name = "department", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
                    String department,
            @WebParam(name = "business", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
                    String business,
            @WebParam(name = "method", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
                    String method,
            @WebParam(name = "args", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
                    byte[] args,
            @WebParam(name = "checkValue", targetNamespace = "http://www.mainsoft.com.cn/mlp/router1/")
                    String checkValue
    );
}
